services:
  flyway:
    image: flyway/flyway:latest

    volumes:
      - /host_mnt/c/XamppOLD/jenkins/Instalacao/MySQL/Jenkins_MySQL/flyway/sql:/flyway/sql

    entrypoint: ["flyway"]

    networks:
      - app-network   # ✅ usa a network

# 👇 MUITO IMPORTANTE: fora da seção services
networks:
  app-network:
    name: app-network