
flyway:
  image: flyway/flyway
  depends_on:
    - mysql-dev
  volumes:
    - ./db/migrations:/flyway/sql
  command: >
    -url=jdbc:mysql://mysql-dev:3306/app_dev
    -user=app_user
    -password=dev123
    migrate
