### PROD
version: "3.8"

services:
  mysql-prod:
    image: mysql:8.0
    container_name: mysql-prod
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: app_prod
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}

    ports:
      - "127.0.0.1:3307:3306"

    volumes:
      - mysql_prod_data:/var/lib/mysql

    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_prod_data:
    driver: local

### Subir o container de PROD
### docker compose --env-file .env -f up -d